<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-18T04:01:42 IST" name="suite1" finished-at="2023-09-18T04:01:55 IST" duration-ms="12978">
    <groups>
    </groups>
    <test started-at="2023-09-18T04:01:42 IST" name="test1" finished-at="2023-09-18T04:01:55 IST" duration-ms="12978">
      <class name="Tests.contact_test">
        <test-method is-config="true" signature="beforeclass()[pri:0, instance:Tests.contact_test@606e4010]" started-at="2023-09-18T04:01:42 IST" name="beforeclass" finished-at="2023-09-18T04:01:42 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method signature="Test_The_ContactFormByFillingItOutAndSubmittingItSuccessfully()[pri:1, instance:Tests.contact_test@606e4010]" started-at="2023-09-18T04:01:42 IST" name="Test_The_ContactFormByFillingItOutAndSubmittingItSuccessfully" finished-at="2023-09-18T04:01:55 IST" duration-ms="12561" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_The_ContactFormByFillingItOutAndSubmittingItSuccessfully -->
        <test-method is-config="true" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:Tests.contact_test@606e4010]" started-at="2023-09-18T04:01:42 IST" name="beforeMethod" finished-at="2023-09-18T04:01:42 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void Tests.contact_test.Test_The_ContactFormByFillingItOutAndSubmittingItSuccessfully() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:Tests.contact_test@606e4010]" started-at="2023-09-18T04:01:55 IST" name="beforeMethod" finished-at="2023-09-18T04:01:55 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void Tests.contact_test.AttemptToSubmitTheContactFormWithInvalidDataAndVerifyTheErrorMessages() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="AttemptToSubmitTheContactFormWithInvalidDataAndVerifyTheErrorMessages()[pri:2, instance:Tests.contact_test@606e4010]" started-at="2023-09-18T04:01:55 IST" name="AttemptToSubmitTheContactFormWithInvalidDataAndVerifyTheErrorMessages" finished-at="2023-09-18T04:01:55 IST" duration-ms="51" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Homepage is not opened expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Homepage is not opened expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at pages.Homepage.HomePageURlOpened(Homepage.java:31)
at Tests.contact_test.AttemptToSubmitTheContactFormWithInvalidDataAndVerifyTheErrorMessages(contact_test.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AttemptToSubmitTheContactFormWithInvalidDataAndVerifyTheErrorMessages -->
      </class> <!-- Tests.contact_test -->
      <class name="Tests.HomePage_Test">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:Tests.HomePage_Test@2d901eb0]" started-at="2023-09-18T04:01:34 IST" name="beforeSuite" finished-at="2023-09-18T04:01:42 IST" duration-ms="7787" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeclass()[pri:0, instance:Tests.HomePage_Test@2d901eb0]" started-at="2023-09-18T04:01:42 IST" name="beforeclass" finished-at="2023-09-18T04:01:42 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method is-config="true" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:Tests.HomePage_Test@2d901eb0]" started-at="2023-09-18T04:01:42 IST" name="beforeMethod" finished-at="2023-09-18T04:01:42 IST" duration-ms="6" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void Tests.HomePage_Test.Verify_That_The_Ve3_global_Homepage_loads_successfully() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="Verify_That_The_Ve3_global_Homepage_loads_successfully()[pri:0, instance:Tests.HomePage_Test@2d901eb0]" started-at="2023-09-18T04:01:42 IST" name="Verify_That_The_Ve3_global_Homepage_loads_successfully" finished-at="2023-09-18T04:01:42 IST" duration-ms="266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_That_The_Ve3_global_Homepage_loads_successfully -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:Tests.HomePage_Test@2d901eb0]" started-at="2023-09-18T04:01:55 IST" name="afterSuite" finished-at="2023-09-18T04:01:56 IST" duration-ms="743" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- Tests.HomePage_Test -->
    </test> <!-- test1 -->
  </suite> <!-- suite1 -->
</testng-results>
